name: test deploy # Workflow 이름

on: # Event 감지
  push:
    branches:
      - master
jobs: # Job 설정
  build:
    runs-on: ubuntu-latest # Job 가상환경 인스턴스
    steps: # Step 설정
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install Dependencies # 의존 파일 설치
        run: yarn install --frozen-lockfile

      - name: Build # React Build
        run: yarn build

      - name: Deploy # Upload build file to S3
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
